sudo: required
services:
  - docker

before_install:
  - docker build -t bobcat1111/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bobcat1111/react-test npm test

after_success:
  - docker build -t bobcat1111/multi-nginx ./nginx
  - docker build -t bobcat1111/multi-server ./server
  - docker build -t bobcat1111/multi-worker ./worker
  - docker build -t bobcat1111/multi-client ./client
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  # take the images and push them to docker hub

  - docker push bobcat1111/multi-nginx
  - docker push bobcat1111/multi-server
  - docker push bobcat1111/multi-worker
  - docker push bobcat1111/multi-client

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: elasticbeanstalk-ap-southeast-2-481154223607
  bucket_path:  "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
